Eternity.Website/Models/ErrorViewModel.cs
namespace Eternity.Website.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Eternity.Website/Controllers/AboutController.cs
using Eternity.Logic.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Eternity.Website.Controllers
{
    public class AboutController : Controller
    {
        private readonly ILogger<AboutController> _logger;
        private readonly IAboutService _aboutService;
        public AboutController(ILogger<AboutController> logger, IAboutService aboutService)
        {
            _logger = logger;
            _aboutService = aboutService;
        }
        public ActionResult Index() 
        {
            return View();
        }
    }
}

Eternity.Website/Controllers/ContactsController.cs
using Eternity.Logic.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Eternity.Website.Controllers
{
    public class ContactsController : Controller
    {
        private readonly ILogger<ContactsController> _logger;
        public ContactsController(ILogger<ContactsController> logger)
        {
            _logger = logger;
        }
        public ActionResult Index() 
        {
            return View();
        }
    }
}

Eternity.Website/Controllers/HomeController.cs
using Eternity.Website.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Eternity.Website.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult f0c4d58042f6706fb41f416c9127141a9848f61b84fb699b02eb60862c5e21b9()//myadminpanel
        {
            _logger.LogInformation("!\n!!\n!!!\tAdminPanel opened");
            return View();
        }
        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Eternity.Website/Controllers/PricesController.cs
using Eternity.DTO.DTOs;
using Eternity.Logic.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Eternity.Website.Controllers
{
    public class PricesController : Controller
    {
        private readonly ILogger<PricesController> _logger;
        private readonly IPriceService _service;
        public PricesController(ILogger<PricesController> logger, IPriceService service)
        {
            _logger = logger;
            _service = service;
        }
        public async Task<ActionResult> Index()
        {
            _logger.LogInformation("PricesController called Index method");
            var myPrices = await _service.GetPrices();
            return View(myPrices);
        }
        public IActionResult Creating()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddPrice(PriceDTO price)
        {
            _logger.LogInformation("PricesController called AddPrice method");
            if (ModelState.IsValid)
            {
                await _service.CreatePrice(price);
                _logger.LogInformation("Redirecting to Index method...");
            }
            return await Task.Run<IActionResult>(() => RedirectToAction("Index", "Prices"));
        }
        public async Task<IActionResult> EditPrice(PriceDTO price, int id)
        {
            _logger.LogInformation("PricesController called EditPrice method");
            await _service.EditPrice(price, id);
            return await Task.Run<IActionResult>(() => RedirectToAction("Index", "Prices"));    //it must return to adminPanel
        }
    }
}

Eternity.Website/Controllers/ServicesController.cs
using Eternity.DTO.DTOs;
using Eternity.Logic.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Eternity.Website.Controllers
{
    public class ServicesController : Controller
    {
        private readonly ILogger<ServicesController> _logger;
        private readonly IServiceService _service;
        public ServicesController(ILogger<ServicesController> logger, IServiceService service)
        {
            _logger = logger;
            _service = service;
        }
        public async Task<ActionResult> Index()
        {
            _logger.LogInformation("ServicesController CALLED Index method");
            var myServices = await _service.ShowServices();
            return View(myServices);
        }
        public IActionResult Editing()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddService(ServiceDTO service)
        {
            _logger.LogInformation("ServicesController CALLED AddService method");
            if (ModelState.IsValid)
            {
                await _service.AddService(service);
                _logger.LogInformation("Redirecting to Index method...");
            }
            return await Task.Run<IActionResult>(() => RedirectToAction("Index", "Services"));
        }
    }
}

Eternity.Website/Controllers/WorksController.cs
using Eternity.DTO.DTOs;
using Eternity.Logic.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Eternity.Website.Controllers
{
    public class WorksController : Controller
    {
        private readonly ILogger<WorksController> _logger;
        private readonly IWorkService _workService;
        public WorksController(ILogger<WorksController> logger, IWorkService workService)
        {
            _logger = logger;
            _workService= workService;
        }
        public async Task<IActionResult> Index()
        {
            _logger.LogInformation("WorksController called Index method");
            var myWorks = await _workService.ShowWorks();
            return View(myWorks);
        }
        public IActionResult Editing()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddWork(WorkDTO work)
        {
            if (ModelState.IsValid)
            {
                await _workService.AddWork(work);
                _logger.LogInformation("Redirecting to Index method...");
            }   
            return await Task.Run<IActionResult>(() => RedirectToAction("Index", "Works"));
        }
    }
}

Eternity.Website/Views/About/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Eternity.Website/Views/Contacts/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Eternity.Website/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Вечность";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>
<div class="own-bg background"></div>
<div class="bg midground"></div>
<div class="bg foreground"></div>

Eternity.Website/Views/Home/f0c4d58042f6706fb41f416c9127141a9848f61b84fb699b02eb60862c5e21b9.cshtml
@{
    ViewData["Title"] = "Администрирование";
}

<div>
    <ul>
        <li>
            <a asp-controller="Works" asp-action="Creating">СОЗДАНИЕ РАБОТЫ</a>
            <a asp-controller="Works" asp-action="Editing">РЕДАКТИРОВАНИЕ РАБОТЫ</a>
        </li>
        <li>
            <a asp-controller="Services" asp-action="Creating">СОЗДАНИЕ УСЛУГИ</a>
            <a asp-controller="Services" asp-action="Editing">ИЗМЕНЕНИЕ УСЛУГИ</a>
        </li>
        <li>
            <a asp-controller="Prices" asp-action="Creating">СОЗДАНИЕ ЦЕНЫ</a>
            <a asp-controller="Prices" asp-action="Editing">ИЗМЕНЕНИЕ ЦЕНЫ</a>
        </li>
        <li>
            <a asp-controller="Contacts" asp-action="Creating">СОЗДАНИЕ КОНТАКТОВ</a>
            <a asp-controller="Contacts" asp-action="Editing">ИЗМЕНЕНИЕ КОНТАКТОВ</a>
        </li>
        <li>
            <a asp-controller="About" asp-action="Creating">СОЗДАНИЕ О НАС</a>
            <a asp-controller="About" asp-action="Editing">ИЗМЕНЕНИЕ О НАС</a>
        </li>
        <!--end of buttons-->
    </ul>
</div>

Eternity.Website/Views/Prices/Creating.cshtml
@using Eternity.DTO.DTOs;
@model PriceDTO

@{
    Layout = "_Layout";
    ViewBag.Title = "СОЗДАНИЕ ЦЕНЫ";
}

<div class="container py-5">
    <div class="row">
        <div class="col-md-12">
            <div class="row justify-content-center">
                <div class="col-md-10">
                    <span class="anchor"></span>
                    <div class="form-control">
                        <div class="card-header">
                            <h3 class="text-center">Добавление цены</h3>
                        </div>
                        <div class="card-body">
                            <form asp-controller="Prices" asp-action="AddPrice" method="post">
                                <div asp-validation-summary="All" style="font-size:23px; font-family:Aleo" class="text-danger text-center"></div>
                                    <label asp-for="Title">Title</label>
                                <div class="form-group">
                                    <input asp-for="Title" class="form-control" placeholder="Заголовок" type="text">
                                </div>
                                    <label asp-for="Description">Description</label>
                                <div class="form-group">
                                    <input asp-for="Description" class="form-control" placeholder="Описание" type="text">
                                </div>
                                <div>
                                    <button class="btn btn-success" type="submit">Добавить</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@*@foreach (var work in Model)
{
    <img class="image-container" src="@string.Format("data:image/png;base64, {0}", Convert.ToBase64String(work))"/>
    <button>Удалить</button>
}
*@

Eternity.Website/Views/Prices/Editing.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Eternity.Website/Views/Prices/Index.cshtml
@using Eternity.DataProvider.Models;
@model List<Price>

@{
    Layout = "_Layout";
    ViewData["Title"] = "Услуги";
}
<div class="own-bg background"></div>
<div class="bg midground"></div>
<div class="bg foreground">
    @{
        @foreach (var price in Model)
        {
            <div class="work-container">
                <p>
                    <i>@price.Id</i>
                    <i>@price.Title</i>
                    <i>@price.Description</i>
                </p>
            </div>
        }
    }
</div>

Eternity.Website/Views/Services/Creating.cshtml
@using Eternity.DTO.DTOs;
@model ServiceDTO

@{
    Layout = "_Layout";
    ViewBag.Title = "СОЗДАНИЕ УСЛУГИ";
}

<div class="container py-5">
    <div class="row">
        <div class="col-md-12">
            <div class="row justify-content-center">
                <div class="col-md-10">
                    <span class="anchor"></span>
                    <div class="form-control">
                        <div class="card-header">
                            <h3 class="text-center">Добавление услуги</h3>
                        </div>
                        <div class="card-body">
                            <form asp-controller="Services" asp-action="AddService" method="post" enctype="multipart/form-data">
                                <div asp-validation-summary="All" style="font-size:23px; font-family:Aleo" class="text-danger text-center"></div>
                                    <label asp-for="Name">Name</label>
                                <div class="form-group">
                                    <input asp-for="Name" class="form-control" placeholder="Название" type="text">
                                </div>
                                    <label asp-for="ServicePhoto">Photo</label>
                                <div class="form-group">
                                    <input asp-for="ServicePhoto" aria-required="true" type="file" accept="image/*" />
                                </div>
                                <div>
                                    <button class="btn btn-success" type="submit">Добавить</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@*@foreach (var work in Model)
{
    <img class="image-container" src="@string.Format("data:image/png;base64, {0}", Convert.ToBase64String(work))"/>
    <button>Удалить</button>
}
*@

Eternity.Website/Views/Services/Editing.cshtml
@using Eternity.DTO.DTOs;
@model ServiceDTO

@{
    Layout = "_Layout";
    ViewBag.Title = "Редактирование";
}

<div class="container py-5">
    <div class="row">
        <div class="col-md-12">
            <div class="row justify-content-center">
                <div class="col-md-10">
                    <span class="anchor"></span>
                    <div class="form-control">
                        <div class="card-header">
                            <h3 class="text-center">Добавление услуги</h3>
                        </div>
                        <div class="card-body">
                            <form asp-controller="Services" asp-action="AddService" method="post" enctype="multipart/form-data">
                                <div asp-validation-summary="All" style="font-size:23px; font-family:Aleo" class="text-danger text-center"></div>
                                    <label asp-for="Name">Name</label>
                                <div class="form-group">
                                    <input asp-for="Name" class="form-control" placeholder="Название" type="text">
                                </div>
                                    <label asp-for="ServicePhoto">Photo</label>
                                <div class="form-group">
                                    <input asp-for="ServicePhoto" aria-required="true" type="file" accept="image/*" />
                                </div>
                                <div>
                                    <button class="btn btn-success" type="submit">Добавить</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@*@foreach (var work in Model)
{
    <img class="image-container" src="@string.Format("data:image/png;base64, {0}", Convert.ToBase64String(work))"/>
    <button>Удалить</button>
}
*@

Eternity.Website/Views/Services/Index.cshtml
@using Eternity.DataProvider.Models;
@model List<Service>

@{
    Layout = "_Layout";
    ViewData["Title"] = "Услуги";
}
<div class="own-bg background"></div>
<div class="bg midground"></div>
<div class="bg foreground">
    @{
        @foreach (var service in Model)
        {
            <div class="work-container">
                <p>
                    <i>@service.Id</i>
                    <i>@service.Name</i>
                    <img class="image-container" src="@string.Format("data:image/png;base64, {0}", Convert.ToBase64String(service.ServicePhoto))"/>
                </p>
            </div>
        }
    }
</div>

Eternity.Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html class="main-div" lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Eternity.Website</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Eternity.Website.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="main-div">
    <header class="header">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm">
            <div class="container-fluid">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                    <!--Main button-->
                        <li class="user-image nav-item">
                            <a class="nav-link text-white" asp-controller="Home" asp-action="Index"><img class="user-image" src="img/logo.png"/></a>
                        </li>
                    <!--end main button-->
                        <!--other buttons in header-->
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Works" asp-action="Index">Наши работы</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Services" asp-action="Index">Услуги</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Prices" asp-action="Index">Цены</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Contacts" asp-action="Index">Контакты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="About" asp-action="Index">О нас</a>
                        </li>
                        <!--end of buttons-->
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
            <div>
                <nav class="navbar-expand-sm">
                    <ul class="navbar-nav flex-grow-1 center-screen">
                        <li class="nav-item center-screen">
                            <a class="nav-link text-white">Свяжитесь с нами:</a>
                        </li>
                        <li class="nav-item center-screen">
                            <a class="nav-link text-white">+375 (29) 692-38-32</a>
                        </li>
                        <li class="nav-item center-screen">
                            <a class="nav-link text-white">+375 (33) 386-53-22</a>
                        </li>
                    </ul> 
                </nav>
            <!--&copy; 2023 - Eternity.Website - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>-->
            </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    </div>
</body>
</html>

Eternity.Website/Views/Works/Creating.cshtml
@using Eternity.DTO.DTOs;
@model WorkDTO

@{
    Layout = "_Layout";
    ViewBag.Title = "СОЗДАНИЕ РАБОТЫ";
}

<div class="container py-5">
    <div class="row">
        <div class="col-md-12">
            <div class="row justify-content-center">
                <div class="col-md-10">
                    <span class="anchor"></span>
                    <div class="form-control">
                        <div class="card-header">
                            <h3 class="text-center">Добавление работы</h3>
                        </div>
                        <div class="card-body">
                            <form asp-controller="Works" asp-action="AddWork" method="post" enctype="multipart/form-data">
                                <div asp-validation-summary="All" style="font-size:23px; font-family:Aleo" class="text-danger text-center"></div>
                                <label asp-for="Image"></label>
                                <div class="form-group">
                                    <input asp-for="Image" aria-required="true" type="file" accept="image/*" />
                                </div>
                                <div>
                                    <button class="btn btn-success" type="submit">Добавить</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@*@foreach (var work in Model)
{
    <img class="image-container" src="@string.Format("data:image/png;base64, {0}", Convert.ToBase64String(work))"/>
    <button>Удалить</button>
}
*@

Eternity.Website/Views/Works/Editing.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Eternity.Website/Views/Works/Index.cshtml
@model List<byte[]>

@{
    Layout = "_Layout";
    ViewData["Title"] = "Наши работы";
}
<div class="own-bg background"></div>
<div class="bg midground"></div>
<div class="bg foreground">
    @{
        int counter = 1;
        @foreach (var work in Model)
        {
                <div class="work-container">
                    <p>
                        <i>@counter</i>
                        <img class="image-container" src="@string.Format("data:image/png;base64, {0}", Convert.ToBase64String(work))"/>
                    </p>
                </div>

            counter++;
        }
    }
</div>